# Imagen base ligera con Node.js 18 en Alpine Linux
FROM node:18-alpine3.15

# Crear y establecer el directorio de trabajo dentro del contenedor
RUN mkdir -p /var/www/pokedex
WORKDIR /var/www/pokedex


# Copiar la raiz del proyecto a la carpeta
# ⚠️ Asegúrate de tener un archivo .dockerignore para evitar copiar node_modules o carpetas innecesarias
COPY . ./var/www/pokedex
# Copiar archivos necesarios de configuración y dependencias
COPY package.json tsconfig.json tsconfig.build.json /var/www/pokedex/

# Instalar TODAS las dependencias
RUN yarn install 
# Compilar la aplicación NestJS 
RUN yarn build

# Crear un usuario no root por seguridad y asignar permisos
RUN adduser --disabled-password pokeuser
RUN chown -R pokeuser:pokeuser /var/www/pokedex

# Cambiar al usuario no root
USER pokeuser

# Limpiar la caché de yarn para reducir el tamaño de la imagen
RUN yarn cache clean --force

# Exponer el puerto donde la app escuchará (por defecto 3000 en NestJS)
EXPOSE 3000

# Comando por defecto al iniciar el contenedor
CMD [ "yarn", "start" ]
